apiVersion: v1
kind: Service
metadata:
  name: backend-challenge-app-service
  labels:
    app: backend-challenge-app
spec:
  selector:
    app: backend-challenge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
